image: node:12

cache:
  paths:
  - node_modules/

before_script:
  - npm ci
  - npx lerna bootstrap --ci

build:
  stage: test
  script:
    - ./package_check.py
    - npm run test
    - npm run lint
