image: node:12

cache:
  paths:
  - node_modules/

before_script:
  - npm ci
  - npx lerna bootstrap --ci

build:
  stage: build
  script:
  - npm run build

test:
  stage: build
  script:
  - npm run test
