/* tslint:disable */
export const memory: WebAssembly.Memory;
export function __wbg_vault_free(a: number): void;
export function __wbg_keyid_free(a: number): void;
export function keyid_new(a: number, b: number): number;
export function keyid_toString(a: number, b: number): void;
export function publickey_new(a: number, b: number): number;
export function publickey_keyId(a: number): number;
export function publickey_validateId(a: number, b: number): number;
export function publickey_toString(a: number, b: number): void;
export function signature_new(a: number, b: number): number;
export function signature_toString(a: number, b: number): void;
export function __wbg_signedmessage_free(a: number): void;
export function signedmessage_new(a: number, b: number, c: number, d: number): number;
export function signedmessage_publicKey(a: number): number;
export function signedmessage_message(a: number, b: number): void;
export function signedmessage_signature(a: number): number;
export function signedmessage_validate(a: number, b: number): number;
export function vault_new(a: number, b: number): number;
export function vault_serialize(a: number, b: number): void;
export function vault_deserialize(a: number, b: number): number;
export function vault_profiles(a: number, b: number): void;
export function vault_activeId(a: number): number;
export function vault_createId(a: number): number;
export function vault_sign(a: number, b: number, c: number, d: number): number;
export function __wbg_publickey_free(a: number): void;
export function __wbg_signature_free(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
